name: Build vitepress
on:
  push:
    branches: [ "vitepress" ]
  workflow_dispatch:


permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_and_deploy:
    if: github.repository_owner == 'HazzazBinFaiz'

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    env:
      BASE_URL: /seu-cse-notes/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'yarn'
        
    - name: Build
      run: yarn install && yarn build
    
    - name: Setup Pages
      uses: actions/configure-pages@v2

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: './notes/.vitepress/dist'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
